# Generated by Django 2.1 on 2018-08-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=50)),
                ('comment', models.TextField()),
            ],
        ),
    ]
